In [ ]:
# ============================
# Group 6 – Data Cleaning Notebook
# Goal: clean & combine all station CSVs into one good DataFrame
# ============================

import os
import pandas as pd
import re

from google.colab import drive
drive.mount("/content/drive")

# BASE_DIR = Import from a Google Drive or Locally. We used a google drive. All data files found in Data folder
print("Base directory:", BASE_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Base directory: /content/drive/MyDrive/Data Science Cert Uoft UW/C4/cleaned_data

In [2]:
# ============================
# Load each station CSV into pandas
# ============================

def load_station(filename: str, station_name: str) -> pd.DataFrame:
    """Load one station CSV and attach a station_name column."""
    path = os.path.join(BASE_DIR, filename)
    df = pd.read_csv(path)
    df["station_name"] = station_name
    return df

toronto   = load_station("toronto.csv",   "Toronto")
vancouver = load_station("vancouver.csv", "Vancouver")
st_george = load_station("st_george.csv", "St George")
edmonton  = load_station("edmonton.csv",  "Edmonton")
inuvik    = load_station("inuvik.csv",    "Inuvik")
halifax   = load_station("halifax.csv",   "Halifax")

for name, df in [
    ("Toronto", toronto),
    ("Vancouver", vancouver),
    ("St George", st_george),
    ("Edmonton", edmonton),
    ("Inuvik", inuvik),
    ("Halifax", halifax),
]:
    print(name, "shape:", df.shape)

Toronto shape: (11076, 29)
Vancouver shape: (6288, 29)
St George shape: (6648, 29)
Edmonton shape: (5892, 29)
Inuvik shape: (9960, 29)
Halifax shape: (8448, 29)

In [3]:
# ============================
# Combine all stations
# ============================

raw_df = pd.concat(
    [toronto, vancouver, st_george, edmonton, inuvik, halifax],
    ignore_index=True
)

print("Combined shape:", raw_df.shape)
print(raw_df["station_name"].value_counts())
raw_df

Combined shape: (48312, 29)
station_name
Toronto      11076
Inuvik        9960
Halifax       8448
St George     6648
Vancouver     6288
Edmonton      5892
Name: count, dtype: int64

,x,y,lat__lat,lon__long,identifier__identifiant,station_id__id_station,period_value__valeur_periode,period_group__groupe_periode,province__province,date,...,rain_units__pluie_unites,snow__neige,snow_units__neige_unites,pressure_sea_level__pression_niveau_mer,pressure_sea_level_units__pression_niveau_mer_unite,pressure_station__pression_station,pressure_station_units__pression_station_unites,wind_speed__vitesse_vent,wind_speed_units__vitesse_vent_unites,station_name
0,-79.40,43.67,43.67,-79.40,6158350.1840.01,6158350,Jan,Monthly,ON,1840-01,...,mm,-9999.9,mm,NaN,hPa,NaN,hPa,NaN,kph,Toronto
1,-79.40,43.67,43.67,-79.40,6158350.1840.02,6158350,Feb,Monthly,ON,1840-02,...,mm,-9999.9,mm,NaN,hPa,NaN,hPa,NaN,kph,Toronto
2,-79.40,43.67,43.67,-79.40,6158350.1840.03,6158350,Mar,Monthly,ON,1840-03,...,mm,-9999.9,mm,NaN,hPa,NaN,hPa,NaN,kph,Toronto
3,-79.40,43.67,43.67,-79.40,6158350.1840.04,6158350,Apr,Monthly,ON,1840-04,...,mm,-9999.9,mm,NaN,hPa,NaN,hPa,NaN,kph,Toronto
4,-79.40,43.67,43.67,-79.40,6158350.1840.05,6158350,May,Monthly,ON,1840-05,...,mm,0.0,mm,NaN,hPa,NaN,hPa,NaN,kph,Toronto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48307,-63.52,44.88,44.88,-63.52,8202251.2020.08,8202251,Aug,Monthly,NS,Aug-20,...,mm,NaN,mm,NaN,hPa,NaN,hPa,NaN,kph,Halifax
48308,-63.52,44.88,44.88,-63.52,8202251.2020.09,8202251,Sep,Monthly,NS,Sep-20,...,mm,NaN,mm,NaN,hPa,NaN,hPa,NaN,kph,Halifax
48309,-63.52,44.88,44.88,-63.52,8202251.2020.10,8202251,Oct,Monthly,NS,Oct-20,...,mm,NaN,mm,NaN,hPa,NaN,hPa,NaN,kph,Halifax
48310,-63.52,44.88,44.88,-63.52,8202251.2020.11,8202251,Nov,Monthly,NS,Nov-20,...,mm,NaN,mm,NaN,hPa,NaN,hPa,NaN,kph,Halifax
48311,-63.52,44.88,44.88,-63.52,8202251.2020.12,8202251,Dec,Monthly,NS,Dec-20,...,mm,NaN,mm,NaN,hPa,NaN,hPa,NaN,kph,Halifax

In [4]:
# ============================
# Standardize / rename key columns
# ============================

col_map = {
    "Date": "date",
    "Date/Time": "date",
    "Year": "year_raw",
    "Month": "month_raw",
    "Day": "day_raw",
    "Max Temp (°C)": "tmax_c",
    "Min Temp (°C)": "tmin_c",
    "Mean Temp (°C)": "tmean_c",
    "Total Precip (mm)": "total_precip_mm",
    "Total Rain (mm)": "rain_mm",
    "Total Snow (cm)": "snow_cm",
    "Snow on Grnd (cm)": "snow_on_ground_cm",
    "Longitude (x)": "longitude",
    "Latitude (y)": "latitude",
    "Elevation (m)": "elevation_m",
}

for old, new in col_map.items():
    if old in raw_df.columns:
        raw_df = raw_df.rename(columns={old: new})

raw_df.columns

Index(['x', 'y', 'lat__lat', 'lon__long', 'identifier__identifiant',
       'station_id__id_station', 'period_value__valeur_periode',
       'period_group__groupe_periode', 'province__province', 'date',
       'temp_mean__temp_moyenne', 'temp_mean_units__temp_moyenne_unites',
       'temp_max__temp_max', 'temp_max_units__temp_max_unites',
       'temp_min__temp_min', 'temp_min_units__temp_min_unites',
       'total_precip__precip_totale',
       'total_precip_units__precip_totale_unites', 'rain__pluie',
       'rain_units__pluie_unites', 'snow__neige', 'snow_units__neige_unites',
       'pressure_sea_level__pression_niveau_mer',
       'pressure_sea_level_units__pression_niveau_mer_unite',
       'pressure_station__pression_station',
       'pressure_station_units__pression_station_unites',
       'wind_speed__vitesse_vent', 'wind_speed_units__vitesse_vent_unites',
       'station_name'],
      dtype='object')

In [5]:
# ============================
# Parse date and cast numeric columns
# ============================

# 5.1 Date
MONTHS = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12"
}

pattern2 = r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\d{2})$"

def convert_date(date):
  '''
  converts date to match the following pattern: YYYY-MM
  '''
  pattern_match = re.match(pattern2, date)
  if pattern_match:
    month, year = pattern_match.groups()
    return f"19{year}-{MONTHS[month]}"
  return date


if "date" in raw_df.columns:
    raw_df['date'] = raw_df['date'].str.strip()
    raw_df['date'] = raw_df['date'].apply(convert_date)
    raw_df["date"] = pd.to_datetime(raw_df["date"], format="%Y-%m", errors="coerce")
else:
    raise ValueError("No 'date' or 'Date' column found – adjust col_map above.")

# Drop rows with no valid date
raw_df = raw_df[~raw_df["date"].isna()].copy()

# 5.2 Create year/month/day from date (clean versions)
raw_df["year"] = raw_df["date"].dt.year
raw_df["month"] = raw_df["date"].dt.month
raw_df["day"] = raw_df["date"].dt.day

# 5.3 Numeric columns – only cast those that exist
numeric_cols = [
    "tmax_c",
    "tmin_c",
    "tmean_c",
    "total_precip_mm",
    "rain_mm",
    "snow_cm",
    "snow_on_ground_cm",
    "longitude",
    "latitude",
    "elevation_m",
]

for col in numeric_cols:
    if col in raw_df.columns:
        raw_df[col] = pd.to_numeric(raw_df[col], errors="coerce")

raw_df.dtypes

x                                                             float64
y                                                             float64
lat__lat                                                      float64
lon__long                                                     float64
identifier__identifiant                                        object
station_id__id_station                                         object
period_value__valeur_periode                                   object
period_group__groupe_periode                                   object
province__province                                             object
date                                                   datetime64[ns]
temp_mean__temp_moyenne                                       float64
temp_mean_units__temp_moyenne_unites                           object
temp_max__temp_max                                            float64
temp_max_units__temp_max_unites                                object
temp_min__temp_min                                            float64
temp_min_units__temp_min_unites                                object
total_precip__precip_totale                                   float64
total_precip_units__precip_totale_unites                       object
rain__pluie                                                   float64
rain_units__pluie_unites                                       object
snow__neige                                                   float64
snow_units__neige_unites                                       object
pressure_sea_level__pression_niveau_mer                       float64
pressure_sea_level_units__pression_niveau_mer_unite            object
pressure_station__pression_station                            float64
pressure_station_units__pression_station_unites                object
wind_speed__vitesse_vent                                      float64
wind_speed_units__vitesse_vent_unites                          object
station_name                                                   object
year                                                            int32
month                                                           int32
day                                                             int32
dtype: object

In [6]:
# ============================
# Data quality checks
# ============================

print("Rows per station:")
print(raw_df["station_name"].value_counts(), "\n")

print("Date range per station:")
print(
    raw_df.groupby("station_name")["date"]
          .agg(["min", "max", "count"])
)

print("\nMissing values per column:")
print(raw_df.isna().sum().sort_values(ascending=False))

Rows per station:
station_name
Toronto      11076
Inuvik        9960
Halifax       8448
St George     6648
Vancouver     6288
Edmonton      5892
Name: count, dtype: int64

Date range per station:
                    min        max  count
station_name
Edmonton     1880-01-01 1999-12-01   5892
Halifax      1871-01-01 1999-12-01   8448
Inuvik       1871-01-01 1999-12-01   9960
St George    1880-01-01 1999-12-01   6648
Toronto      1840-01-01 1999-12-01  11076
Vancouver    1896-01-01 1999-12-01   6288

Missing values per column:
wind_speed__vitesse_vent                               36408
rain__pluie                                            35436
total_precip__precip_totale                            35436
snow__neige                                            35436
pressure_sea_level__pression_niveau_mer                32688
pressure_station__pression_station                     32688
temp_max__temp_max                                     21816
temp_min__temp_min                                     21816
temp_mean__temp_moyenne                                21816
period_value__valeur_periode                               0
period_group__groupe_periode                               0
x                                                          0
identifier__identifiant                                    0
y                                                          0
lat__lat                                                   0
lon__long                                                  0
temp_min_units__temp_min_unites                            0
temp_max_units__temp_max_unites                            0
date                                                       0
temp_mean_units__temp_moyenne_unites                       0
province__province                                         0
station_id__id_station                                     0
rain_units__pluie_unites                                   0
total_precip_units__precip_totale_unites                   0
pressure_sea_level_units__pression_niveau_mer_unite        0
snow_units__neige_unites                                   0
pressure_station_units__pression_station_unites            0
wind_speed_units__vitesse_vent_unites                      0
station_name                                               0
year                                                       0
month                                                      0
day                                                        0
dtype: int64

In [7]:
# ============================
# Final clean DataFrame for group use
# ============================

# Sort for sanity
clean_df = raw_df.sort_values(["station_name", "date"]).reset_index(drop=True)

print("Final clean shape:", clean_df.shape)
clean_df

Final clean shape: (48312, 32)

,x,y,lat__lat,lon__long,identifier__identifiant,station_id__id_station,period_value__valeur_periode,period_group__groupe_periode,province__province,date,...,pressure_sea_level__pression_niveau_mer,pressure_sea_level_units__pression_niveau_mer_unite,pressure_station__pression_station,pressure_station_units__pression_station_unites,wind_speed__vitesse_vent,wind_speed_units__vitesse_vent_unites,station_name,year,month,day
0,-113.6000,53.3000,53.3000,-113.6000,3012206.1880.01,3012206,Jan,Monthly,AB,1880-01-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,1,1
1,-113.6000,53.3000,53.3000,-113.6000,3012206.1880.02,3012206,Feb,Monthly,AB,1880-02-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,2,1
2,-113.6000,53.3000,53.3000,-113.6000,3012206.1880.03,3012206,Mar,Monthly,AB,1880-03-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,3,1
3,-113.6000,53.3000,53.3000,-113.6000,3012206.1880.04,3012206,Apr,Monthly,AB,1880-04-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,4,1
4,-113.6000,53.3000,53.3000,-113.6000,3012206.1880.05,3012206,May,Monthly,AB,1880-05-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48307,-122.8769,49.2517,49.2517,-122.8769,1101200.1999.12,1101200,Dec,Monthly,BC,1999-12-01,...,NaN,hPa,NaN,hPa,NaN,kph,Vancouver,1999,12,1
48308,-123.1800,49.1800,49.1800,-123.1800,1108380.1999.12,1108380,Dec,Monthly,BC,1999-12-01,...,NaN,hPa,NaN,hPa,NaN,kph,Vancouver,1999,12,1
48309,-123.1200,49.3000,49.3000,-123.1200,1108446.1999.12,1108446,Dec,Monthly,BC,1999-12-01,...,-9999.9,hPa,-9999.9,hPa,NaN,kph,Vancouver,1999,12,1
48310,-123.1819,49.1950,49.1950,-123.1819,1108447.1999.12,1108447,Dec,Monthly,BC,1999-12-01,...,1022.1,hPa,1021.6,hPa,14.0,kph,Vancouver,1999,12,1
48311,-123.1900,49.3500,49.3500,-123.1900,1108824.1999.12,1108824,Dec,Monthly,BC,1999-12-01,...,1022.8,hPa,-9999.9,hPa,NaN,kph,Vancouver,1999,12,1

In [8]:
df = clean_df.copy()
df.head(3)

,x,y,lat__lat,lon__long,identifier__identifiant,station_id__id_station,period_value__valeur_periode,period_group__groupe_periode,province__province,date,...,pressure_sea_level__pression_niveau_mer,pressure_sea_level_units__pression_niveau_mer_unite,pressure_station__pression_station,pressure_station_units__pression_station_unites,wind_speed__vitesse_vent,wind_speed_units__vitesse_vent_unites,station_name,year,month,day
0,-113.6,53.3,53.3,-113.6,3012206.1880.01,3012206,Jan,Monthly,AB,1880-01-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,1,1
1,-113.6,53.3,53.3,-113.6,3012206.1880.02,3012206,Feb,Monthly,AB,1880-02-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,2,1
2,-113.6,53.3,53.3,-113.6,3012206.1880.03,3012206,Mar,Monthly,AB,1880-03-01,...,NaN,hPa,NaN,hPa,NaN,kph,Edmonton,1880,3,1

In [9]:
rename_map = {
    "lat__lat": "latitude",
    "lon__long": "longitude",
    "province__province": "province",
    "station_id__id_station": "station_id",
    "identifier__identifiant": "identifier",
    "period_value__valeur_periode": "period_label",
    "period_group__groupe_periode": "period_group",
    "rain__pluie": "rain_mm",
    "snow__neige": "snow_mm",
    "pressure_sea_level__pression_niveau_mer": "pressure_sea_level_hpa",
    "pressure_station__pression_station": "pressure_station_hpa",
    "wind_speed__vitesse_vent": "wind_speed_kph",
}

for old, new in rename_map.items():
    if old in df.columns:
        df = df.rename(columns={old: new})

df.columns.tolist()

['x',
 'y',
 'latitude',
 'longitude',
 'identifier',
 'station_id',
 'period_label',
 'period_group',
 'province',
 'date',
 'temp_mean__temp_moyenne',
 'temp_mean_units__temp_moyenne_unites',
 'temp_max__temp_max',
 'temp_max_units__temp_max_unites',
 'temp_min__temp_min',
 'temp_min_units__temp_min_unites',
 'total_precip__precip_totale',
 'total_precip_units__precip_totale_unites',
 'rain_mm',
 'rain_units__pluie_unites',
 'snow_mm',
 'snow_units__neige_unites',
 'pressure_sea_level_hpa',
 'pressure_sea_level_units__pression_niveau_mer_unite',
 'pressure_station_hpa',
 'pressure_station_units__pression_station_unites',
 'wind_speed_kph',
 'wind_speed_units__vitesse_vent_unites',
 'station_name',
 'year',
 'month',
 'day']

In [10]:
cols_to_drop = [
    "x",
    "y",
    "rain_units__pluie_unites",
    "snow_units__neige_unites",
    "pressure_sea_level_units__pression_niveau_mer_unite",
    "pressure_station_units__pression_station_unites",
    "wind_speed_units__vitesse_vent_unites",
]

df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

df.columns

Index(['latitude', 'longitude', 'identifier', 'station_id', 'period_label',
       'period_group', 'province', 'date', 'temp_mean__temp_moyenne',
       'temp_mean_units__temp_moyenne_unites', 'temp_max__temp_max',
       'temp_max_units__temp_max_unites', 'temp_min__temp_min',
       'temp_min_units__temp_min_unites', 'total_precip__precip_totale',
       'total_precip_units__precip_totale_unites', 'rain_mm', 'snow_mm',
       'pressure_sea_level_hpa', 'pressure_station_hpa', 'wind_speed_kph',
       'station_name', 'year', 'month', 'day'],
      dtype='object')

In [11]:
import pandas as pd

df["date"] = pd.to_datetime(df["date"], errors="coerce")
df = df[~df["date"].isna()].copy()

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month

In [12]:
import numpy as np

# Pick candidate numeric columns by name pattern
candidate_numeric = [
    c for c in df.columns
    if any(k in c.lower() for k in [
        "temp", "rain", "snow", "precip", "pressure", "wind"
    ])
]

print("Candidate numeric columns:", candidate_numeric)

for col in candidate_numeric:
    df[col] = df[col].replace(
        ["-9999.9", "-99999.9", -9999.9, -99999.9],
        np.nan
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[candidate_numeric].dtypes

Candidate numeric columns: ['temp_mean__temp_moyenne', 'temp_mean_units__temp_moyenne_unites', 'temp_max__temp_max', 'temp_max_units__temp_max_unites', 'temp_min__temp_min', 'temp_min_units__temp_min_unites', 'total_precip__precip_totale', 'total_precip_units__precip_totale_unites', 'rain_mm', 'snow_mm', 'pressure_sea_level_hpa', 'pressure_station_hpa', 'wind_speed_kph']

temp_mean__temp_moyenne                     float64
temp_mean_units__temp_moyenne_unites        float64
temp_max__temp_max                          float64
temp_max_units__temp_max_unites             float64
temp_min__temp_min                          float64
temp_min_units__temp_min_unites             float64
total_precip__precip_totale                 float64
total_precip_units__precip_totale_unites    float64
rain_mm                                     float64
snow_mm                                     float64
pressure_sea_level_hpa                      float64
pressure_station_hpa                        float64
wind_speed_kph                              float64
dtype: object

In [13]:
core_cols = [
    "station_name",
    "station_id",
    "province",
    "latitude",
    "longitude",
    "date",
    "year",
    "month",
] + candidate_numeric

core_cols = [c for c in core_cols if c in df.columns]

final_df = df[core_cols].sort_values(["station_name", "date"]).reset_index(drop=True)

print("Final group DataFrame shape:", final_df.shape)
final_df.head()

Final group DataFrame shape: (48312, 21)

,station_name,station_id,province,latitude,longitude,date,year,month,temp_mean__temp_moyenne,temp_mean_units__temp_moyenne_unites,...,temp_max_units__temp_max_unites,temp_min__temp_min,temp_min_units__temp_min_unites,total_precip__precip_totale,total_precip_units__precip_totale_unites,rain_mm,snow_mm,pressure_sea_level_hpa,pressure_station_hpa,wind_speed_kph
0,Edmonton,3012206,AB,53.3,-113.6,1880-01-01,1880,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Edmonton,3012206,AB,53.3,-113.6,1880-02-01,1880,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Edmonton,3012206,AB,53.3,-113.6,1880-03-01,1880,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Edmonton,3012206,AB,53.3,-113.6,1880-04-01,1880,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Edmonton,3012206,AB,53.3,-113.6,1880-05-01,1880,5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import pandas as pd

df = final_df.copy()

# Drop all columns that are purely "units" columns
unit_cols = [c for c in df.columns if "units" in c.lower()]
print("Dropping unit columns:", unit_cols)

df = df.drop(columns=unit_cols)

print("New shape after dropping units:", df.shape)
df.head()

Dropping unit columns: ['temp_mean_units__temp_moyenne_unites', 'temp_max_units__temp_max_unites', 'temp_min_units__temp_min_unites', 'total_precip_units__precip_totale_unites']
New shape after dropping units: (48312, 17)

,station_name,station_id,province,latitude,longitude,date,year,month,temp_mean__temp_moyenne,temp_max__temp_max,temp_min__temp_min,total_precip__precip_totale,rain_mm,snow_mm,pressure_sea_level_hpa,pressure_station_hpa,wind_speed_kph
0,Edmonton,3012206,AB,53.3,-113.6,1880-01-01,1880,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Edmonton,3012206,AB,53.3,-113.6,1880-02-01,1880,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Edmonton,3012206,AB,53.3,-113.6,1880-03-01,1880,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Edmonton,3012206,AB,53.3,-113.6,1880-04-01,1880,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Edmonton,3012206,AB,53.3,-113.6,1880-05-01,1880,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
print("Rows per station:")
print(df["station_name"].value_counts(), "\n")

print("Date range per station:")
print(
    df.groupby("station_name")["date"]
      .agg(["min", "max", "count"])
)

print("\nNon-missing counts for key variables:")
print(
    df[[
        "temp_mean__temp_moyenne",
        "temp_max__temp_max",
        "temp_min__temp_min",
        "total_precip__precip_totale",
        "rain_mm",
        "snow_mm",
        "wind_speed_kph"
    ]].notna().sum()
)

Rows per station:
station_name
Toronto      11076
Inuvik        9960
Halifax       8448
St George     6648
Vancouver     6288
Edmonton      5892
Name: count, dtype: int64

Date range per station:
                    min        max  count
station_name
Edmonton     1880-01-01 1999-12-01   5892
Halifax      1871-01-01 1999-12-01   8448
Inuvik       1871-01-01 1999-12-01   9960
St George    1880-01-01 1999-12-01   6648
Toronto      1840-01-01 1999-12-01  11076
Vancouver    1896-01-01 1999-12-01   6288

Non-missing counts for key variables:
temp_mean__temp_moyenne        25481
temp_max__temp_max             25523
temp_min__temp_min             25513
total_precip__precip_totale    12007
rain_mm                        12046
snow_mm                        12016
wind_speed_kph                 10856
dtype: int64

In [16]:
# Make sure station_id is stored as string for Parquet
if "station_id" in df.columns:
    df["station_id"] = df["station_id"].astype(str)

df.dtypes["station_id"]

dtype('O')

In [17]:
# rounding lat and lon columns to 2 decimal places
df["latitude"] = df["latitude"].round(1)
df["longitude"] = df["longitude"].round(1)

In [18]:
# dropping station_id col
df.drop(columns=["station_id"], inplace=True)

In [19]:
rearranged_df = df.groupby(["station_name", "date"])[df.columns.difference(["station_name", "date"])].agg(lambda x: x.dropna().iloc[0] if not x.dropna().empty else np.nan).reset_index()

In [21]:
BASE_DIR = "/content/drive/MyDrive/Data Science Cert Uoft UW/C4/cleaned_data"

csv_path = BASE_DIR + "/clean_monthly_data.csv"        # DATASET USED FOR THE DASHBOARD

rearranged_df.to_csv(csv_path, index=False)

print("Clean CSV saved at:")
print(csv_path)

Clean CSV saved at:
/content/drive/MyDrive/Data Science Cert Uoft UW/C4/cleaned_data/clean_monthly_data.csv

In [ ]:
# ============================
# Quick structural EDA on cleaned monthly data
# ============================

print("Shape of cleaned monthly data:", df.shape)
print("\nColumn types:")
print(df.dtypes)

print("\nRows per station:")
print(df["station_name"].value_counts(), "\n")

print("Date range per station:")
print(
    df.groupby("station_name")["date"]
      .agg(["min", "max", "count"])
      .sort_index()
)

print("\nNon-missing counts for main climate variables:")
print(
    df[[
        "temp_mean__temp_moyenne",
        "temp_max__temp_max",
        "temp_min__temp_min",
        "total_precip__precip_totale",
        "rain_mm",
        "snow_mm",
        "wind_speed_kph"
    ]].notna().sum()
)

In [ ]:
# ============================
# Quick structural EDA on cleaned monthly data
# ============================

print("Shape of cleaned monthly data:", df.shape)
print("\nColumn types:")
print(df.dtypes)

print("\nRows per station:")
print(df["station_name"].value_counts(), "\n")

print("Date range per station:")
print(
    df.groupby("station_name")["date"]
      .agg(["min", "max", "count"])
      .sort_index()
)

print("\nNon-missing counts for main climate variables:")
print(
    df[[
        "temp_mean__temp_moyenne",
        "temp_max__temp_max",
        "temp_min__temp_min",
        "total_precip__precip_totale",
        "rain_mm",
        "snow_mm",
        "wind_speed_kph"
    ]].notna().sum()
)

In [ ]:
# ============================
# Annual aggregation per station (for ML / dashboard)
# ============================

annual_df = (
    df.groupby(["station_name", "station_id", "province", "latitude", "longitude", "year"])
      .agg(
          avg_temp_mean   = ("temp_mean__temp_moyenne", "mean"),
          avg_temp_max    = ("temp_max__temp_max", "mean"),
          avg_temp_min    = ("temp_min__temp_min", "mean"),
          total_precip_mm = ("total_precip__precip_totale", "sum"),
          total_rain_mm   = ("rain_mm", "sum"),
          total_snow_mm   = ("snow_mm", "sum"),
          avg_wind_kph    = ("wind_speed_kph", "mean")
      )
      .reset_index()
      .sort_values(["station_name", "year"])
)

print("Annual-level table shape:", annual_df.shape)
annual_df.head()

In [ ]:
annual_csv_path = BASE_DIR + "/weather_annual_features.csv"
annual_df.to_csv(annual_csv_path, index=False)

print("Annual features CSV saved at:")
print(annual_csv_path)

In [ ]:
# ============================================
# FULL WEATHER EDA BLOCK  (One Big Cell)
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns

# Use your existing clean df
eda_df = df.copy()

print("=== Clean Weather DataFrame ===")
print(eda_df.shape)
print(eda_df.head(3))

# ============================================
# 1. DISTRIBUTIONS OF CORE VARIABLES
# ============================================

numeric_vars = [
    "temp_mean__temp_moyenne",
    "temp_max__temp_max",
    "temp_min__temp_min",
    "total_precip__precip_totale",
    "rain_mm",
    "snow_mm",
    "wind_speed_kph"
]

fig, axes = plt.subplots(len(numeric_vars), 1, figsize=(10, 30))
for i, col in enumerate(numeric_vars):
    sns.histplot(eda_df[col], kde=True, ax=axes[i], bins=40)
    axes[i].set_title(f"Distribution: {col}")
plt.tight_layout()
plt.show()

# ============================================
# 2. TEMPERATURE TRENDS OVER TIME PER STATION
# ============================================

plt.figure(figsize=(14, 6))
sns.lineplot(
    data=eda_df,
    x="date",
    y="temp_mean__temp_moyenne",
    hue="station_name",
    estimator="mean"
)
plt.title("Monthly Mean Temperature Over Time (By Station)")
plt.xlabel("Year")
plt.ylabel("Mean Temp (°C)")
plt.show()

# ============================================
# 3. PRECIPITATION TRENDS OVER TIME
# ============================================

plt.figure(figsize=(14, 6))
sns.lineplot(
    data=eda_df,
    x="date",
    y="total_precip__precip_totale",
    hue="station_name",
    estimator="mean"
)
plt.title("Total Monthly Precipitation Over Time (By Station)")
plt.xlabel("Year")
plt.ylabel("Precip (mm)")
plt.show()

# ============================================
# 4. SEASONAL TEMPERATURE CYCLE (MONTHLY AVERAGE)
# ============================================

seasonal = (
    eda_df.groupby(["station_name", "month"])["temp_mean__temp_moyenne"]
          .mean()
          .reset_index()
)

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=seasonal,
    x="month",
    y="temp_mean__temp_moyenne",
    hue="station_name",
    marker="o"
)
plt.title("Seasonal Temperature Pattern (Average by Month)")
plt.xlabel("Month (1–12)")
plt.ylabel("Mean Temp (°C)")
plt.show()

# ============================================
# 5. SEASONAL PRECIPITATION CYCLE
# ============================================

seasonal_precip = (
    eda_df.groupby(["station_name", "month"])["total_precip__precip_totale"]
          .mean()
          .reset_index()
)

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=seasonal_precip,
    x="month",
    y="total_precip__precip_totale",
    hue="station_name",
    marker="o"
)
plt.title("Seasonal Precipitation Pattern (Average by Month)")
plt.xlabel("Month (1–12)")
plt.ylabel("Precip (mm)")
plt.show()

# ============================================
# 6. TEMPERATURE vs PRECIPITATION RELATIONSHIP
# ============================================

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=eda_df,
    x="temp_mean__temp_moyenne",
    y="total_precip__precip_totale",
    hue="station_name",
    alpha=0.6
)
plt.title("Relationship Between Temperature & Precipitation")
plt.xlabel("Mean Temperature (°C)")
plt.ylabel("Total Monthly Precipitation (mm)")
plt.show()

# ============================================
# 7. CORRELATION HEATMAP (CLIMATE VARIABLES)
# ============================================

corr = eda_df[numeric_vars].corr()

plt.figure(figsize=(10, 7))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap of Climate Variables")
plt.show()

# ============================================
# 8. SUMMARY STATISTICS PER STATION
# ============================================

station_summary = (
    eda_df.groupby("station_name")
        .agg(
            n_months=("date", "count"),
            mean_temp=("temp_mean__temp_moyenne", "mean"),
            min_temp=("temp_min__temp_min", "min"),
            max_temp=("temp_max__temp_max", "max"),
            annual_precip_mean=("total_precip__precip_totale", "mean"),
            avg_wind=("wind_speed_kph", "mean"),
        )
        .reset_index()
)

print("\n=== STATION SUMMARY STATISTICS ===")
print(station_summary)

# ============================================
# 9. PRINT KEY EDA TAKEAWAYS (TEXT)
# ============================================

print("\n=== KEY EDA PATTERNS YOU CAN PUT IN REPORT/SLIDES ===")

print("""
1. Temperature cycles clearly show seasonal shape for all stations,
   but the amplitude differs sharply:
   - Inuvik shows the coldest winters and largest seasonal swing.
   - Vancouver has very mild seasonal variation.

2. Precipitation patterns differ by coast vs inland:
   - Vancouver has high winter precipitation.
   - Halifax shows moderate but consistent precipitation.
   - Toronto & Edmonton have lower precipitation overall.

3. Relationship between temperature and precipitation is weak
   (seen in scatterplots and correlations),
   meaning temperature alone will NOT predict precipitation.
   This supports using a multi-feature ML model.

4. Wind speeds vary strongly by station,
   with coastal stations tending to have higher average wind.

5. Yearly trends show gradual warming over centuries for Toronto,
   Edmonton, and Inuvik — important for dashboard storytelling.

6. Missing values increase in older years for all stations,
   so visualizations should filter to ranges with good data.
""")

### Exploratory Climate Patterns & Dashboard-Ready Insights

This section summarizes the exploratory patterns observed in the cleaned Canadian climate dataset. The dataset represents monthly climate observations from six stations distributed across the country: Edmonton, Halifax, Inuvik, St George, Toronto, and Vancouver. The combined dataset includes more than four thousand monthly observations and contains temperature variables, precipitation variables, snowfall metrics, wind, pressure (limited in early years), and geographic descriptors such as latitude, longitude, and province. After cleaning and harmonizing column names, the dataset is now consistent and station-comparable, which enables meaningful visual and statistical exploration.

The first broad pattern in the data is the strong and predictable seasonality visible across all six stations. Monthly averages show that temperatures follow a highly cyclical pattern: coldest conditions occur in January and February, while the warmest months consistently fall in July and August. However, the size of the seasonal swing differs dramatically across stations. Inuvik, located far north, shows the most extreme variation, with very cold winters and only mild summers. Vancouver is at the opposite end of the spectrum, with mild winters and moderate summers, showing far less temperature amplitude. Toronto displays warm summers and moderately cold winters, acting as a middle ground between oceanic and continental climates. This seasonal structure will be an important foundation for dashboards that highlight yearly or month-by-month comparisons.

Precipitation behavior also shows meaningful geographic structure. Coastal stations—particularly Vancouver—experience significantly higher precipitation volumes, with rainfall peaking mainly in the winter months. Halifax shows a more balanced pattern, with rain distributed relatively evenly across the year but with noticeable increases in spring and fall. Inland stations such as Edmonton, St George, and Toronto show lower precipitation overall, and a greater share of winter precipitation appears as snowfall. Inuvik and Edmonton have long winter periods where snowfall plays a dominant role, and rain becomes relevant only in the warmer months. These coastal-versus-inland distinctions are ideal candidates for comparative dashboard elements.

When exploring relationships between climate variables, the temperature metrics show very high correlations with each other, which is expected since mean temperature is closely tied to maximum and minimum values. Precipitation variables, however, show weaker relationships with temperature. Scatter plots confirm that warmer months do not necessarily produce more or less precipitation. Rain and total precipitation correlate strongly, as expected, but snowfall behaves differently. Snowfall increases sharply in stations with colder winter periods and does not correlate with rainfall in any meaningful way. This lack of linear dependence suggests that precipitation modeling will require more than temperature inputs. Features such as latitude, longitude, elevation, seasonal grouping, and historical precipitation averages will likely improve predictive models.

Long-term missingness patterns are also visible. Older records, especially those from the 19th century (notably early Toronto and St George data), have more missing values, particularly for wind speed and atmospheric pressure. Temperature and precipitation data are far more complete across all years. For future dashboards, it will be useful to either restrict visualizations to periods with high data completeness or to visually mark where missing data occurs.

The dataset naturally lends itself to dashboard visualizations. Clear candidates include seasonal temperature curves to show warm–cold cycles across stations, monthly precipitation breakdowns (rain versus snow), overall temperature distributions, and comparative climate summaries between stations. A station-comparison page could allow users to overlay temperature or precipitation histories for two stations at once. A seasonal dashboard page could highlight patterns by month across all stations, showing how dramatically Canadian climates differ. An exploratory page with scatter plots and a correlation heatmap would communicate the strength and weakness of relationships among climate variables.

Overall, the dataset captures a rich set of climate behaviors across Canada. The strong seasonal structures, combined with geographic contrasts between northern, inland, and coastal stations, provide enough depth for meaningful climate dashboards and for building predictive models based on annual features. These EDA insights will guide the selection of dashboard visuals in the next phase and support any later machine-learning experimentation on precipitation prediction or station-level climate behavior.

##. Exploratory Data Analysis (EDA) & Dashboard Design Recommendations

This section summarizes the exploratory analysis carried out on the cleaned monthly climate dataset, covering six Canadian weather stations: **Edmonton, Halifax, Inuvik, St George, Toronto, and Vancouver**.  
These insights directly inform the design of our interactive dashboard and guide the selection of visual elements for the final deliverable.

---

### 1 Overview of the Cleaned Dataset

- **Total rows:** 4,092  
- **Stations covered:** 6  
- **Time span:** Varies by station (earliest observations begin in the 1840s for Toronto; other stations start later)  
- **Variables included:**
  - Temperature metrics (mean, max, min)  
  - Rainfall, snowfall, total precipitation  
  - Wind speed, atmospheric pressure (limited completeness)  
  - Latitude, longitude, province  
  - Derived **year** and **month** features  

The dataset is monthly and standardized across stations, making it appropriate for both **trend analysis** and **seasonal comparisons**.

---

### 2 Key Patterns Identified

#### 1. Strong Seasonal Temperature Cycles

All six stations show clear and predictable seasonality:

- **Summer peaks:** July–August  
- **Winter lows:** January–February  

Amplitude varies significantly:

- **Inuvik**: Most extreme (very cold winters, cool summers)  
- **Vancouver**: Mildest climate, limited winter severity  
- **Toronto**: Warm summers, moderately cold winters  

This highlights the broad climatic diversity across Canada.

---

#### 2. Precipitation Varies Strongly by Geography

Geographical factors play a major role:

- **Vancouver**: Highest precipitation, especially in winter  
- **Halifax**: Moderate but consistent precipitation year-round  
- **Toronto, Edmonton, St George**: Lower precipitation totals  

These contrasts should be emphasized in comparative dashboard views.

---

#### 3. Temperature–Precipitation Relationship is Weak

Correlation analysis shows:

- Temperature variables (mean, max, min) are **highly correlated with each other**  
- Precipitation variables (total, rain, snow) correlate as expected  
- **Temperature does not strongly predict precipitation**

**Implication:**  
A precipitation prediction model must incorporate **multi-feature inputs**—temperature alone is insufficient.

---

#### 4. Seasonal Precipitation Cycles

Monthly station-level averages reveal:

- **Vancouver**: Heavy winter rainfall (Nov–Jan)  
- **Toronto**: Balanced precipitation with increases in spring & late fall  
- **St George**: Generally low precipitation, especially during summer  
- **Inuvik & Edmonton**: Low precipitation dominated by snowfall in winter  

These patterns are ideal candidates for seasonal comparison pages.

---

#### 5. Missing Value Patterns

- Older records (pre-1900) have substantial missingness  
- Wind and pressure observations are sparse in earlier decades  
- Temperature variables are the most complete overall  

**Recommendation:**  
Filter dashboards to **years with high completeness** to avoid distortion.

---

### 3 Recommended Dashboard Pages  
*(For Power BI / Looker Studio / Tableau)*

---

#### ** Page 1 — “Station Overview”**

**Purpose:** Provide a high-level summary of each climate station.

**Visuals:**

- Time Series: Mean Temperature (°C) per station  
- Time Series: Total Monthly Precipitation (mm) per station  
- KPI Cards:
  - Avg annual temperature  
  - Avg annual precipitation  
  - Station coordinates (lat/long)  
  - Station active year range (min–max)  

This page serves as the dashboard landing page.

---

#### ** Page 2 — “Seasonal Climate Patterns”**

**Purpose:** Compare seasonal behaviour across all stations.

**Visuals:**

- Seasonal mean temperature curves (month vs. temp)  
- Seasonal precipitation curves (month vs. precipitation)  
- Optional: Separate rainfall vs. snowfall cycles  

Ideal for highlighting cross-Canada seasonal variation.

---

#### ** Page 3 — “Climate Relationships”**

**Purpose:** Analyze relationships between climate variables.

**Visuals:**

- Scatter plot: Mean Temperature vs Total Precipitation  
- Correlation heatmap of climate features  
- Histograms: temperature metrics, precipitation, snowfall  

Useful for identifying potential predictors for modeling.

---

#### ** Page 4 — “Station Comparator”**

**Purpose:** Allow users to compare any two stations.

**Visuals:**

- Overlayed time series for selected stations  
- Comparative metrics:
  - Mean temperature difference  
  - Annual precipitation difference  
  - Snowfall contrast  
- Map with station latitude/longitude  

---

#### ** Page 5 — “Future ML Model Page”**

**Purpose:** Integrate predictive modeling results.

**Inputs:**

- Latitude, longitude  
- Elevation  
- Annual climate metrics  

**Outputs:**

- Predicted annual precipitation  
- Optional: Confidence intervals  

This page will be populated once the machine learning model is developed.

---

### 3.4 Dataset Hand-off for Next Steps

Two datasets are now available for the team:

1. **weather_clean_monthly_ANALYSIS.csv**  
   - Full monthly dataset  
   - Cleaned, standardized, ready for visualization  

2. **weather_annual_features.csv**  
   - Aggregated annual-level dataset  
   - Designed for ML modeling and trend analysis  

Both are located in the shared **Group 6 Google Drive** folder.

---

### 3.5 Summary for the Team

- The dataset is fully cleaned, standardized, and ready for analysis.  
- Seasonal and geographic climate differences are clearly visible.  
- Temperature and precipitation show **independent behaviour**, an important modeling insight.  
- Dashboard page designs are aligned with assignment deliverables.  
- Monthly dataset is ready for **dashboard development** (Neva, Adrian, Mary).  
---